name: 'dev'

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  actions: read # For the consecutivness

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
    - uses: mktcode/consecutive-workflow-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  amplify:
    runs-on: ubuntu-latest
    name: Deploy Environment
    needs: [ consecutiveness ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::694525212676:role/GitHub
          role-session-name: GitHubDeploy
          aws-region: us-east-1
      - name: Setup Profile
        run: |
          aws configure set region us-east-1 --profile amplify
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile amplify
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile amplify
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile amplify
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy
        shell: bash
        run: ./scripts/amplify-deploy.sh dev
